### ISSUE TITLE
Cross-reference spine: typed relationships + cmr-refs marker convention, enforced (EPIC #138 DoD gap)

### ISSUE THREAD

**Issue by kushin77** [kushin77/agent-orchestrator#384]
Parent: #138

## GOAL

Build the **cross-reference spine** that EPIC #138 is named for: typed relationship edges in
the institutional knowledge index, a **`cmr-refs` marker convention** that is *enforced and
validated* (not advisory), and RCA objects as **first-class nodes** with `caused-by` /
`mitigates` relationships — then gate all of it so a broken cross-reference or a dead
`cmr-refs` target is a conformance failure, never a silent skip. Success = the catalog carries
a deterministic `relationships` list, the gate passes on the committed tree **and** fails when
a target is mutated, and `make verify` is green.

## Constraints

- One lane owns `governance/knowledge/`, the new gate script, and the gate wiring. Touch only
  your lane's files; do not reformat `Makefile`/`scripts/verify.sh` beyond your insertion.
- Cross-reference **generation is deterministic and reproducible**: no timestamps in the edge
  list, edges sorted, byte-stable across rebuilds.
- Do not seed `cmr-refs:` markers into files another lane owns (e.g. `docs/CANNIBALIZATION.md`,
  the ADR index). Seed them only in files this lane owns.
- Every markdown link you add must resolve; `vendor/` paths in backticks only.

## Context

EPIC #138 (M24) children #139–#143 delivered the index **nodes** (`governance/knowledge/`:
`model.py` `KnowledgeItem` = id/kind/path/title/provenance/tags/keywords; `catalog.json` top
keys = counts/coverage/findings/generated_at/item_count/items/repo/schema — **no relationships
key**), provenance, secret policy, conformance, lessons, remediation and the board gate. The
**edges** were never built. The raw data to turn into edges already exists in-repo:

- ADR front-matter `supersedes:` (e.g. ADR-0012) → `supersedes` edges.
- `.board/snapshot.json` issue `Parent:`/`Blocked-by:` → `parent-of` / `blocked-by` edges.
- `governance/lessons/ledger.jsonl` — records of kind `incident`/`rca`/`corrective-action`/
  `lesson`, with fields `origin`, `incident`, `rca`, `corrective_actions`, `artifact` →
  `caused-by` (rca→incident), `mitigates` (corrective-action→rca, lesson→incident), `origin`
  (rca/incident→issue|pr|commit).
- `governance/lessons/rca/RCA-*.md` — the RCA artifacts (already carry the required sections).
- `cmr-refs:` markers in tracked markdown → `refs` edges (this lane defines the marker syntax
  and validates every target exists).

## Deliverables (files this lane owns)

1. `governance/knowledge/model.py` — add a `Relationship` dataclass (from_id, type, to_id,
   optional `via`) and a **closed** relationship vocabulary, e.g.
   `supersedes | parent-of | blocked-by | caused-by | mitigates | origin | refs | part-of |
   implements`; add `relationships` to `Index.as_dict()` / `from_dict()`.
2. `governance/knowledge/crossref.py` (new) — deterministic builder: reads the ADR front-matter,
   `.board/snapshot.json`, `governance/lessons/ledger.jsonl` and tracked-`cmr-refs:` markers,
   emits a **sorted, deduplicated** edge list.
3. `governance/knowledge/indexer.py` — call the crossref builder during build so the catalogue
   carries `relationships`.
4. `governance/knowledge/catalog.json` — **regenerated** with the new `relationships` key
   (build twice and assert byte-identical to prove determinism).
5. `governance/knowledge/README.md` — document the `cmr-refs:` marker syntax and the closed
   relationship vocabulary.
6. `docs/CROSS-REFERENCE-SPINE.md` (new) — the normative convention doc (marker syntax, where
   it is valid, what a valid target is, the vocabulary, and the no-silent-skip rule).
7. `scripts/check-cross-reference.sh` (new, `chmod +x`) — the gate; see below.
8. `Makefile` + `scripts/verify.sh` — wire the gate (`cross-reference` check) into the gate of
   record; insert `scripts/verify.sh`'s entry immediately AFTER the `'knowledge-index|…'` line.
9. `docs/README.md` — one row for `docs/CROSS-REFERENCE-SPINE.md`.

## The `cmr-refs:` convention (define and enforce exactly this)

- A marker is a markdown line matching `cmr-refs:` followed by a comma-separated list of
  targets. Target forms: `ADR-NNNN`, `GR-N`, `#N` (issue), `RCA-NNNN`, `LESSON-NNNN`, `INC-NNNN`,
  or a repo-relative path in backticks.
- The gate must: parse every marker in tracked `.md` files (outside `vendor/`, `.research/`,
  `.git/`), reject malformed markers (bad syntax, unknown kind prefix), and **reject any target
  that does not resolve** (file exists, or entity id present in the catalogue / board snapshot /
  ledger). A `cmr-refs:` target that cannot be validated is a FAIL, never a skip.

## The gate `scripts/check-cross-reference.sh`

Follow the repo gate style (`scripts/check-knowledge-index.sh`, `scripts/check-fleet-contract.sh`):
bash, `set -u`, `root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"`, tri-state exit
`0 OK / 1 NOT-OK / 2 CANNOT-ASSESS`, and a **negative control that mutates its own input**.
It must FAIL (exit 1) naming the file and the missing thing when:

- the catalogue is missing the `relationships` key, or an edge uses a type outside the closed
  vocabulary, or an edge endpoint does not resolve;
- a `cmr-refs:` marker is malformed, or names a target that does not resolve (dead reference);
- the determinism assertion fails (two builds differ).

Negative control: copy the convention doc to a temp dir, change one `cmr-refs:` target to a
bogus id, assert the text changed (`assert mutated != original`) and the sha256 differs, and
require the gate to refuse it. If the mutant passes, print FAIL and exit non-zero. Exit 2 only
when it cannot assess. Temp dirs: `mkdir "/tmp/ao138x.$$.$(date +%s)"` — never three consecutive
X (the repo's docs-lint rejects `XXX` in `.sh`).

## House rules that WILL fail the gate if you break them

- `bash -n` on every `.sh`; every `.py` compiles (`python3 -m py_compile`); every `.json`
  parses; no trailing whitespace in `.md`/`.sh`/`.py`/`.yaml`/`Makefile`; no
  `TODO`/`FIXME`/`HACK`/`XXX` word-boundary markers in `.sh`/`.py`; every relative markdown link
  resolves; `pytest governance/knowledge/tests` and `pytest governance/lessons/tests` stay green.

## Verification (run in your lane worktree; cwd-independent — use absolute paths)

```
bash -n scripts/check-cross-reference.sh
python3 -m py_compile governance/knowledge/crossref.py governance/knowledge/model.py governance/knowledge/indexer.py
python3 governance/knowledge/cli.py build && python3 governance/knowledge/cli.py build   # determinism: identical
bash scripts/check-knowledge-index.sh
bash scripts/check-cross-reference.sh
python3 -m pytest -p no:cacheprovider -q governance/knowledge/tests governance/lessons/tests
bash scripts/check-docs.sh
```

Redirect ALL output to a uniquely named /tmp log and read it back with the file reader (the
shared terminal interleaves other lanes' output; a sibling's Ctrl-C can kill a run — detach with
`setsid` or re-run). Do NOT run `make verify` (the orchestrator runs it once per lane).

**Mutation proof you must capture:** gate rc 0 on your tree → break a `cmr-refs:` target →
confirm rc != 0 with a message naming the file + missing target → restore → confirm sha256
matches the original. Also run the built-in negative control. Report exact commands and real
output.

## Commit

```
git -C <worktree> add <explicit file list — never -A>
git -C <worktree> -c user.name=agent-copilot-crossref -c user.email=agent+copilot-crossref@agents.invalid commit -F <message-file>
```

Subject ends with `(#<issue>)`; body carries the literal trailer
`Refs kushin77/agent-orchestrator#<issue>`. If `.board/snapshot.json` is modified, `git -C
<worktree> checkout -- .board/snapshot.json` BEFORE committing — never stage it. Leave
`vendor/CMR` alone. Do NOT push.

## Report back (concise, factual)

1. The relationship vocabulary and the exact edge counts by type you generated.
2. The `cmr-refs:` marker syntax you defined and where you seeded it.
3. Files created/modified with line counts; whether `catalog.json` regenerated byte-identically.
4. The gate's assertions + the exact mutation-proof transcript (commands, real rc, messages,
   before/after sha256).
5. Exact output of every check above.
6. Commit sha + `git show --stat`.
7. Anything not completed, and why.
Never claim a check passed unless you ran it and can quote its output.

**Comment by kushin77** [comment]
## Closure evidence — #384 (cross-reference spine)

**Merged:** PR #392, squash-merge commit `8334b15` (`8334b15c82740a471894c92b18060964d7cc7cab`). Source branch `issue-384` deleted. Issue auto-closed by `Closes #384`.

**Lane:** `knowledge-crossref`, session `27d5ec7a38dd`, branch `issue-384` cut from `09ae20c`, agent `copilot-crossref`.

### What it delivered (the EPIC's missing edges)

The index had *nodes* (items + provenance) but no *edges*. This lane added the **spine**:

- `governance/knowledge/model.py` — `Relationship` dataclass + closed vocabulary
  `supersedes | parent-of | blocked-by | caused-by | mitigates | origin | refs | part-of | implements`.
- `governance/knowledge/crossref.py` — deterministic, sorted, deduplicated edge builder from ADR
  `supersedes:` front-matter, `.board/snapshot.json` `Parent:`/`Blocked-by:`,
  `governance/lessons/ledger.jsonl` (incident/rca/corrective-action/lesson), and tracked `cmr-refs:` markers.
- `governance/knowledge/catalog.json` regenerated — **74 typed relationships** (`parent-of` 24,
  `blocked-by` 10, `caused-by` 5, `mitigates` 14, `origin` 10, `refs` 11).
- `docs/CROSS-REFERENCE-SPINE.md` + `governance/knowledge/README.md` — the `cmr-refs:` marker syntax
  and vocabulary; `scripts/check-cross-reference.sh` — the gate, wired into `make verify`.

### Gate of record — clean detached worktree pinned to the merge commit

```
$ git worktree add --detach /tmp/ao138-final-proof 8334b15c82740a471894c92b18060964d7cc7cab
$ cd /tmp/ao138-final-proof && make verify
...
verify: PASS (31 of 31 checks)
```

`.verify/attestation.json`: `result=PASS`, `exit_code=0`, `check_count=31`, `git_sha=8334b15c…`;
the `cross-reference` check is present in `checks[]` with `rc=0`, alongside `knowledge-index`,
`conformance`, `lessons`, `remediation`, `board-gate`. Lane-level: `PASS (30 of 30)` at `1e10791`
(pre-merge) and `PASS (31 of 31)` at `adab649` after merging the advanced `master`.

### Mutation proof — the gate can genuinely fail

```
before sha256 = 3010049f21c2e8b749748c66be59cf0f33a501fa98beca89baf18b086b67ee0f
mutate RCA-0001 -> RCA-9999
  FAIL  docs/CROSS-REFERENCE-SPINE.md:20: cmr-refs target 'RCA-9999' does not resolve (ledger record RCA-9999)
  FAIL  docs/CROSS-REFERENCE-SPINE.md:86: cmr-refs target 'RCA-9999' does not resolve (ledger record RCA-9999)
check-cross-reference: FAIL — cross-reference spine violated (see above)
GATE_RC=1
restore -> sha256 = 3010049f21c2e8b749748c66be59cf0f33a501fa98beca89baf18b086b67ee0f  (== before)
```

Determinism: `relationships` byte-identical across two wall-clock builds; full index byte-identical
under a fixed timestamp (edges carry no timestamps).

### Honest finding — one gate finding on the PR body (disclosed, not hidden)

`scripts/check-pr-contract.sh --body-file …` reported `pr-body-unreproduced-pre-existing-red`:
the PR body's `## Pre-existing red` section described a real reproduction in prose but did not
use the gate's required `Reproduce:`-line + fenced-output-block shape. The reproduction itself is
real: `pytest governance/knowledge/tests governance/lessons/tests` fails at **collection**
(`ImportError: cannot import name 'CODE_BOARD_INCIDENT_EXEMPT' from 'model'`) because both
packages define `model.py` and both conftests prepend their dir to `sys.path[0]` — reproduced
identically on a clean worktree of base `09ae20c`, and each suite passes in isolation
(`governance/knowledge` 47 passed, `governance/lessons` 129 passed). This is why
`scripts/pytest-suites.txt` runs suites in isolation. The merged history is unaffected (the
commit carries its `Refs` trailer and the landed audit is clean); the body-format finding is
recorded here rather than erased.
